# Generated by Django 3.2 on 2023-01-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='num_of_pages',
            new_name='number_of_pages',
        ),
    ]
